unfreeze_format: start_step
verbose: True
unfreeze_schedule:
  - start_step: 0
    params:
      - head.bias
      - head.weight
      - aa_embed.weight
  - start_step: 1
    params:
      - decoder.*
  - start_step: 2
    params:
      - "*"
