#!/usr/bin/env python
"""Compute training-step overrides from the prepared split metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--train-batch-size", type=int, default=16)
    parser.add_argument("--grad-accumulation", type=int, default=4)
    parser.add_argument("--epochs", type=int, default=6)
    parser.add_argument("--min-steps", type=int, default=0)
    parser.add_argument("--out", required=True)
    parser.add_argument("--finetune-config")
    return parser.parse_args()


# Per-layer encoder-first gradual-unfreeze phases, mirroring the InstaNovo-P
# manuscript schedule (instadeepai/InstaNovo-P,
# configs/finetune_scheduler/finetune_schedule_gu_encoder-decoder-v2.yaml):
# head + embeddings, then encoder layers from top (8) to bottom (0), then decoder
# layers from top to bottom. The spectrum/input encoders (peak/charge/latent) are
# unfrozen with the first encoder phase so InstaNovo 1.2.x's freeze-all-then-unfreeze
# scheduler does not leave them frozen. Each entry is (fraction-of-training_steps,
# params); the manuscript spans ~10 transition epochs, so we keep its relative
# ordering and scale the phase boundaries to whatever training budget this run uses.
UNFREEZE_PHASES = [
    (0.0, ["head.bias", "head.weight", "aa_embed.weight"]),
    (0.1, ["peak_encoder.*", "charge_encoder.*", "latent_spectrum", "encoder.layers.8.*"]),
    (0.2, ["encoder.layers.7.*", "encoder.layers.6.*"]),
    (0.3, ["encoder.layers.5.*", "encoder.layers.4.*"]),
    (0.4, ["encoder.layers.3.*", "encoder.layers.2.*"]),
    (0.5, ["encoder.layers.1.*", "encoder.layers.0.*"]),
    (0.7, ["decoder.layers.8.*", "decoder.layers.7.*"]),
    (0.8, ["decoder.layers.6.*", "decoder.layers.5.*", "decoder.layers.4.*"]),
    (0.9, ["decoder.layers.3.*", "decoder.layers.2.*", "decoder.layers.1.*", "decoder.layers.0.*"]),
]


def write_finetune_config(path: Path, training_steps: int) -> None:
    """Write a step-based, per-layer encoder-first finetuning schedule for InstaNovo 1.2.x.

    Realises the InstaNovo-P gradual-unfreezing strategy: head + sequence/spectrum
    embeddings first, then the encoder layers from the top down, then the decoder
    layers from the top down (encoder fully before decoder). Phase start steps are
    placed at fixed fractions of ``training_steps`` so the relative ordering is
    preserved regardless of the dataset/epoch budget. ``start_step`` is used because
    InstaNovo's FinetuneScheduler is built without ``steps_per_epoch`` and so cannot
    use epoch-based formats.
    """
    lines = [
        "# Per-layer encoder-first gradual unfreeze (InstaNovo-P style), generated by",
        "# scripts/04_make_training_overrides.py: head + embeddings, then encoder layers",
        "# 8 -> 0, then decoder layers 8 -> 0, with phase start steps scaled to",
        f"# training_steps (={training_steps} for the split this was generated from).",
        "unfreeze_format: start_step",
        "verbose: True",
        "unfreeze_schedule:",
    ]
    last_step = 0
    for fraction, params in UNFREEZE_PHASES:
        step = max(last_step, round(fraction * training_steps))
        last_step = step
        lines.append(f"  - start_step: {step}")
        lines.append("    params:")
        for pattern in params:
            quoted = f'"{pattern}"' if "*" in pattern else pattern
            lines.append(f"      - {quoted}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    metadata = json.loads(Path(args.metadata).read_text(encoding="utf-8"))
    train_count = int(metadata["split_counts"]["train"])
    steps_per_epoch = max(1, train_count // args.train_batch_size)
    training_steps = max(args.min_steps, steps_per_epoch * args.epochs)
    warmup_iters = max(5, int(round(training_steps * 0.05)))
    validation_interval = steps_per_epoch
    checkpoint_interval = validation_interval

    lines = [
        f"training_steps={training_steps}",
        f"warmup_iters={warmup_iters}",
        f"validation_interval={validation_interval}",
        f"checkpoint_interval={checkpoint_interval}",
        f"console_logging_steps={max(5, validation_interval // 4)}",
        f"tensorboard_logging_steps={max(5, validation_interval // 4)}",
    ]
    output = Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    effective_batch_size = args.train_batch_size * args.grad_accumulation
    print(f"train_count={train_count}")
    print(f"train_batch_size={args.train_batch_size}")
    print(f"grad_accumulation={args.grad_accumulation}")
    print(f"effective_batch_size={effective_batch_size}")
    print(f"steps_per_epoch={steps_per_epoch}")
    print("\n".join(lines))
    if args.finetune_config:
        write_finetune_config(Path(args.finetune_config), training_steps)
        print(f"Updated finetune schedule: {args.finetune_config}")


if __name__ == "__main__":
    main()
